version: '3.8'
services:
  postgres:
    container_name: postgres-intuit
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data
    ports:
      - '5433:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
